### ISSUE TITLE
How to use this container

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/smartmontools#1]
I already tried fiddling with your container but I give up :( I was able to make email notification work by running ssmtp inside the container but I don't understand how the smartmontools actually work. What do I need to put in smartd.conf and how do I test that it's working if there are no errors/warning in my drive?

Also, I noticed that the environment variables inside the ssmt.conf file are not working at all. When authenticating against the mail server, the container passes the literal text of the environment variable, not the value. When I do echo ${env variable} inside the container I get the correct value that I pass from the host env variables to the container env variables though. So the workaround to this is to simply put everything in plain text without using variables. I'm not sure how you made your setup work with this.

**Comment by kevindd992002** [comment]
@mdhiggins, just wanted to follow-up on this in case  you've missed it? I'm the first one to post something in this so I'm not sure if you're monitoring it.

**Comment by mdhiggins** [comment]
Here is my config for smartmontools

```
  smartmontools:
    image: mdhiggins/smartmontools
    privileged: true
    container_name: smartmontools
    volumes:
      - /opt/appdata/smartmontools/smartd.conf:/etc/smartd.conf:ro
      - /opt/appdata/smartmontools/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
```

I ended up not using the environment variables and just including the info in the config files directly cause I was having the same issue
